[package]
name = "mpx-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
file-size = "1.0.3"
thiserror = "1.0.59"
walkdir = "2.5.0"
